### ISSUE TITLE
How to run the code on the cRIO?

### ISSUE THREAD

**Issue by technillogue** [robotpy/robotpy-crio#2]
This isn't an actual issue, I'd just like to ask any active devs how to run the robotpy code on the cRIO. The FRC driver station says that it doesn't see the robot code. The "gettign started" part of the wiki says to "Copy all files and directories in the distribution's `robot` directory (which doesn't exists) to the root (top level) directory on the robot.". Based on the note, I just copied the whole folder to the robot's root. The FRC driver station says in way of explenation,"There is no user code running on the robot. 1. If developping, use the tools to start it. 2. if ready for competition, build and deploy it as a startup application."

Any advice?

**Comment by virtuald** [comment]
Run install.py to copy the files to the cRio.

The wiki instructions are correct, but ambiguous (will try to change them soon). You need to copy the robot folder in the distribution zip file to the robot. This is what install.py will do for you.
