### ISSUE TITLE
os has no attribute 'WIFSIGNALED'

### ISSUE THREAD

**Issue by ariovistus** [robotpy/robotpy-crio#4]
just tried rpdb2 on the crio and got above error at subprocess.py:1360.

v 2013.2

**Comment by virtuald** [comment]
Can you post a full call stack? It looks like it's trying to start a new process, which probably won't work correctly.

**Comment by ariovistus** [comment]
Traceback (most recent call last):
  File "/c/py/boot.py", line 38, in main
    robot = **import**("robot")
  File "/c/py/robot.py", line 8, in <module>
    import rpdb2
  File "/c/lib/python3.2/site-packages/rpdb2.py", line 266, in <module>
    import subprocess
  File "/lib/python3.2/subprocess.py", line 637, in <module>
    class Popen(object):
  File "/lib/python3.2/subprocess.py", line 1360, in Popen
    def _handle_exitstatus(self, sts, _WIFSIGNALED=os.WIFSIGNALED,
AttributeError: 'module' object has no attribute 'WIFSIGNALED'

**Comment by virtuald** [comment]
Sorry about not addressing this, somehow got lost in the noise. Given 2015 changes, I'll close this.

**Comment by ariovistus** [comment]
I loled when I read this in the robotpy mailing list. no worries.

**Comment by virtuald** [comment]
Github email is a lot better nowadays, we'll do better with bug reports this year. :)
