### ISSUE TITLE
PWM.sip should be inheriting LiveWindowSendable, ITableListener

### ISSUE THREAD

**Issue by mattyork** [robotpy/robotpy-crio#7]
I can fix this and send a pull request after this weekends comp.

[PWM.sip](https://github.com/robotpy/robotpy/blob/2014/Packages/wpilib/sip/PWM.sip#L24):

```
class PWM : SensorBase
```

[PWM.h](https://github.com/robotpy/wpilib/blob/master/PWM.h#L32):

```
class PWM : public SensorBase, public ITableListener, public LiveWindowSendable
```

This might be a problem for other ITableListener and LiveWindowSendable children. Should check all those guys, too.

We found this because this Python in our code:

```
LiveWindow.GetInstance().AddActuator('subsystem', 'name', Talon(1))
```

Failed with this error:

```
File "/c/py/robot.py", line 19, in init 
  self.lw.AddActuator('subsystem', 'name', self.motor) TypeError: LiveWindow.AddActuator(): 
arguments did not match any overloaded call: 
   overload 1: argument 3 has unexpected type 'Talon' 
   overload 2: argument 2 has unexpected type 'str'
```

`overload  1` is the correct overloaded AddActuator method, but RobotPy doesn't know that Talon is a LiveWindowSendable.

**Comment by virtuald** [comment]
Closed due to age.
